"""empty message

Revision ID: 9a7ab4b24eec
Revises: 7e0fa0af05a6
Create Date: 2023-08-17 12:49:20.775147

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9a7ab4b24eec'
down_revision = '7e0fa0af05a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cruise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=255), nullable=True))

    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    with op.batch_alter_table('cruise', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
