version: '3'

services:
  db:
    image: postgres:14

    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: relecloud
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

    volumes:
      - postgres-data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d relecloud"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    network_mode: service:db

volumes:
  postgres-data: