name: Python Format Check
on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'lab/**'
      - 'assets/**'

jobs:
    checks-format:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
                python-version: 3.11
                cache: 'pip'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-dev.in
        - name: Lint with ruff
          run: ruff .
        - name: Check formatting with black
          run: black . --check --verbose


