name: Python check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_package:
    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
        - uses: actions/checkout@v3
        - name: Setup python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python_version }}
            architecture: x64
        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements-dev.txt
            playwright install --with-deps
        - name: Run Pytest tests
          run: python3 -m pytest -s
          env:
            DBHOST: localhost
            DBUSER: postgres
            DBPASS: postgres
            DBNAME: postgres